DROP DATABASE IF EXISTS cs4471;
CREATE DATABASE cs4471;
USE cs4471;

CREATE TABLE user (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	token VARCHAR(255) UNIQUE
);
